import { Link } from "wouter"
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Scale, AlertTriangle } from "lucide-react"

export default function TermsOfServicePage() {
  const effectiveDate = "2026-07-24"

  return (
    <div className="max-w-4xl mx-auto space-y-6 sm:space-y-8 animate-in fade-in duration-500">
      <section className="rounded-2xl border border-border/60 bg-card/70 backdrop-blur p-5 sm:p-7">
        <div className="flex flex-wrap items-center gap-3 mb-3">
          <div className="p-2 rounded-lg bg-primary/10 border border-primary/20">
            <Scale className="w-5 h-5 text-primary" />
          </div>
          <h1 className="text-2xl sm:text-3xl font-display font-bold tracking-tight">Terms of Service</h1>
          <Badge variant="outline" className="font-mono text-[10px] tracking-widest border-primary/40 text-primary">
            EFFECTIVE {effectiveDate}
          </Badge>
        </div>
        <p className="text-sm text-muted-foreground leading-relaxed">
          These terms govern your use of TENNIS MATRIX AI. By accessing or using the platform,
          you agree to these terms.
        </p>
      </section>

      <Card className="glass-panel border-border">
        <CardHeader>
          <CardTitle className="text-lg">Use of Service</CardTitle>
          <CardDescription>
            Platform access is provided for analytical and informational use.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-3 text-sm text-muted-foreground leading-relaxed">
          <p>You must use the service in compliance with applicable laws and regulations.</p>
          <p>
            You agree not to misuse, disrupt, reverse engineer, or attempt unauthorized access to
            the platform or related systems.
          </p>
          <p>
            We may update, suspend, or remove features without prior notice to maintain platform
            stability, safety, or compliance.
          </p>
        </CardContent>
      </Card>

      <Card className="glass-panel border-border">
        <CardHeader>
          <CardTitle className="text-lg">Model Output and No Guarantee</CardTitle>
          <CardDescription>
            Predictions are probabilistic and can be wrong.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-3 text-sm text-muted-foreground leading-relaxed">
          <p>
            Outputs, confidence indicators, and directional calls are generated by statistical
            models and historical data. They are not guarantees of future results.
          </p>
          <p>
            You are solely responsible for any decisions or actions you take based on platform
            output.
          </p>
          <div className="rounded-xl border border-warning/30 bg-warning/5 p-3.5 flex items-start gap-2.5">
            <AlertTriangle className="w-4 h-4 text-warning shrink-0 mt-0.5" />
            <p className="text-xs sm:text-sm text-muted-foreground">
              Nothing on this platform constitutes financial, investment, legal, or professional
              advice.
            </p>
          </div>
        </CardContent>
      </Card>

      <Card className="glass-panel border-border">
        <CardHeader>
          <CardTitle className="text-lg">Liability, Availability, and Changes</CardTitle>
        </CardHeader>
        <CardContent className="space-y-3 text-sm text-muted-foreground leading-relaxed">
          <p>
            The service is provided "as is" and "as available" without warranties of any kind,
            express or implied.
          </p>
          <p>
            To the maximum extent permitted by law, TENNIS MATRIX AI is not liable for indirect,
            incidental, consequential, or special damages arising from your use of the service.
          </p>
          <p>
            We may revise these terms from time to time. Continued use after changes are posted
            constitutes acceptance of the updated terms.
          </p>
        </CardContent>
      </Card>

      <p className="text-xs text-muted-foreground text-center">
        Also review our <Link href="/privacy" className="text-primary hover:underline">Privacy Policy</Link> and <Link href="/responsible-gambling" className="text-primary hover:underline">Responsible Gambling / Disclaimer</Link>.
      </p>
    </div>
  )
}